import { Octokit } from "@octokit/rest";

import type { FixResult } from "./fixAgent";
import type { TriageResult } from "./triageAgent";

export interface PRResult {
  success: boolean;
  prUrl: string;
  prNumber: number;
  branchName: string;
  message: string;
}

function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : "Unknown error";
}

export async function runPRAgent(
  owner: string,
  repo: string,
  triage: TriageResult,
  fix: FixResult,
): Promise<PRResult> {
  try {
    const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

    const { data: repoData } = await octokit.repos.get({ owner, repo });
    const defaultBranch = repoData.default_branch;
    const { data: refData } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    const sha = refData.object.sha;

    const branchName = `fix/auto-${triage.category}-${Date.now()}`;
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha,
    });

    const fileName = `fixes/auto-fix-${triage.runId}.md`;
    const fileContent = Buffer.from(`# Auto-Fix Report

## Failure Summary
- **Run ID:** ${triage.runId}
- **Workflow:** ${triage.runName}
- **Category:** ${triage.category}
- **Severity:** ${triage.severity}
- **Summary:** ${triage.summary}

## Suggested Fix
${triage.suggestedFix}

## Code Changes
\`\`\`
${fix.codeChanges}
\`\`\`

## Files Affected
${fix.filesAffected.map((file) => `- ${file}`).join("\n")}

## Confidence
${fix.confidence}

---
*Auto-generated by Intelligent DevOps Orchestrator*
`).toString("base64");

    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: fileName,
      message: `fix: auto-fix for ${triage.category} in run ${triage.runId}`,
      content: fileContent,
      branch: branchName,
    });

    const { data: pr } = await octokit.pulls.create({
      owner,
      repo,
      title: `[Auto-Fix] ${triage.severity.toUpperCase()}: ${triage.summary}`,
      body: `## Automated Fix by Intelligent DevOps Orchestrator

**Failure Category:** ${triage.category}
**Severity:** ${triage.severity}
**Confidence:** ${fix.confidence}

### What happened
${triage.summary}

### What this PR does
${fix.fixDescription}

### Suggested Code Changes
\`\`\`
${fix.codeChanges}
\`\`\`

### Files Likely Affected
${fix.filesAffected.map((file) => `- ${file}`).join("\n")}

---
> ⚠️ This PR was auto-generated. Human review required before merging.
> Generated by [Intelligent DevOps Orchestrator](https://github.com)`,
      head: branchName,
      base: defaultBranch,
    });

    return {
      success: true,
      prUrl: pr.html_url,
      prNumber: pr.number,
      branchName,
      message: "PR created successfully",
    };
  } catch (error) {
    return {
      success: false,
      prUrl: "",
      prNumber: 0,
      branchName: "",
      message: getErrorMessage(error),
    };
  }
}
